version: '3.2'
services:
  discord_gay_detector:
    container_name: discord_gay_detector
    restart: unless-stopped
    build: .
    volumes:
      - type: bind
        source: /srv/discord-gay-detector/database.db3
        target: /app/database.db3
      - type: bind
        source: /srv/discord-gay-detector/.env
        target: /app/.env
      - type: bind
        source: /srv/discord-gay-detector/bot.log
        target: /app/bot.log
